"""empty message

Revision ID: 733b26591931
Revises: 
Create Date: 2025-02-17 20:47:43.018236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733b26591931'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tron_info',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('bandwidth', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_tron_info_address'), 'tron_info', ['address'], unique=True)
    op.create_index(op.f('ix_tron_info_guid'), 'tron_info', ['guid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tron_info_guid'), table_name='tron_info')
    op.drop_index(op.f('ix_tron_info_address'), table_name='tron_info')
    op.drop_table('tron_info')
    # ### end Alembic commands ###
